# Generated by Django 2.0.2 on 2018-04-30 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date(2018, 4, 30))),
                ('end_date', models.DateField(default=datetime.date(2018, 4, 30))),
                ('positioon', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
    ]
