# Generated by Django 2.0.2 on 2018-04-30 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date(2018, 4, 30))),
                ('end_date', models.DateField(default=datetime.date(2018, 4, 30))),
                ('major', models.CharField(max_length=100)),
                ('second_major', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Me',
        ),
    ]
