# Generated by Django 2.0.2 on 2018-04-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0003_auto_20180430_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
    ]
